export const questions = [
    {
    type: 'rage',
    question: "Recordar",
    desc: "Por favor, tómese un momento para recordar un evento en el que experimentó enojo o irritación.",
    options: [],
  }, 
  {
    type: 'rage',
    question: "¿Qué fue lo que te hizo sentir enojo en esa ocasión?",
    options: ['Otra persona', 'Una situación', 'Algo que sucedió', 'No sé'],
  },
  {
    type: 'rage',
    question: "¿En qué lugar te encontrabas cuando sentiste ese enojo?",
    options: ['En casa', 'En el trabajo', 'En una reunión social', 'En otro lugar'],
  }, 
    {
    type: 'rage',
    question: "¿Quiénes estaban involucrados en esa situación?",
    options: ['Familiares', 'Amigos', 'Colegas', 'Otros'],
  }, 
  {
    type: 'rage',
    question: "¿Recuerdas qué desencadenó tu enojo?",
    options: ['Palabras', 'Acciones', 'Ambas', 'No recuerdo'],
  }, 
  {
    type: 'rage',
    question: "¿Cómo te sentiste emocionalmente en ese momento?",
    options: ['Furioso', 'Frustrado', 'Irritado', 'Triste', 'Otro'],
  }, 
  {
    type: 'rage',
    question: "¿Qué hiciste o dijiste en respuesta a ese enojo?",
    options: ['Converse', 'Discutí', 'Guarde silencio', 'Llore', 'Respondí violentamente'],
  }, 
  {
    type: 'rage',
    question: "¿Consideras que manejaste bien la situación en retrospectiva en retrospectiva?",
    options: ['Bien', 'Podría haber sido mejor', 'Mal', 'Muy mal'],
  }, 
  {
    type: 'demographic',
    question: "¿Cual es tu edad?",
    options: ['Bajo 18', '18-24', '25-34', '35-44', '45-54', '55-64', '65 o mas'],
  },
  {
    type: 'demographic',
    question: '¿Cual es tu genero?',
    options: ['Masculino', 'Femenino', 'No-binario', 'Prefiero no decir'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 1/37',
    image: '/images/images1.jpg',
    options: ['Celos', 'Alarmado', 'Arrogante', 'Odio'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 2/37',
    image: '/images/images2.jpg',
    options: ['Juguetón', 'Reconfortante', 'Irritado', 'Aburrido'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 3/37',
    image: '/images/images3.jpg',
    options: ['Aterrado', 'Molesto', 'Arrogante', 'Fastidiado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 4/37',
    image: '/images/images4.jpg',
    options: ['Bromeando', 'Nervioso', 'Deseo', 'Convencido'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 5/37',
    image: '/images/images5.jpg',
    options: ['Bromeando', 'Insistente', 'Entretenido', 'Relajado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 6/37',
    image: '/images/images6.jpg',
    options: ['Irritado', 'Sarcástico', 'Preocupado', 'Amigable'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 7/37',
    image: '/images/images7.jpg',
    options: ['Espantado', 'Fantaseando', 'Impaciente', 'Alarmado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 8/37',
    image: '/images/images8.jpg',
    options: ['Arrepentido', 'Amigable', 'Incómodo', 'Desanimado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 9/37',
    image: '/images/images9.jpg',
    options: ['Desalentado', 'Aliviado', 'Tímido', 'Entusiasmado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 10/37',
    image: '/images/images10.jpg',
    options: ['Fastidiado', 'Hostil', 'Horrorizado', 'Preocupado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 11/37',
    image: '/images/images11.jpg',
    options: ['Cauteloso', 'Insistente', 'Aburrido', 'Espantado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 12/37',
    image: '/images/images12.jpg',
    options: ['Aterrado', 'Entretenido', 'Arrepentido', 'Coqueto'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 13/37',
    image: '/images/images13.jpg',
    options: ['Indiferente', 'Averagonzado', 'Escéptico', 'Desanimado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 14/37',
    image: '/images/images14.jpg',
    options: ['Decidido', 'Expectante', 'Amenazante', 'Tímido'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 15/37',
    image: '/images/images15.jpg',
    options: ['Irritado', 'Decepcionado', 'Deprimido', 'Acusador'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 16/37',
    image: '/images/images16.jpg',
    options: ['Comtemplativo', 'Nervioso', 'Motivado', 'Entretenido'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 17/37',
    image: '/images/images17.jpg',
    options: ['Irritado', 'Considerado', 'Alentador', 'Empática'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 18/37',
    image: '/images/images18.jpg',
    options: ['Indeciso', 'Cariñosa', 'Juguetón', 'Espantado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 19/37',
    image: '/images/images19.jpg',
    options: ['Decidido', 'Entretenido', 'Espantado', 'Aburrido'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 20/37',
    image: '/images/images20.jpg',
    options: ['Arrogante', 'Agradecido', 'Sarcástico', 'Dudosa'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 21/37',
    image: '/images/images21.jpg',
    options: ['Dominante', 'Amigable', 'Culpable', 'Horrorizado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 22/37',
    image: '/images/images22.jpg',
    options: ['Averagonzado', 'Fantaseando', 'Confundido', 'Alarmado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 23/37',
    image: '/images/images23.jpg',
    options: ['Preocupado', 'Agradecido', 'Insistente', 'Suplicante'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 24/37',
    image: '/images/images24.jpg',
    options: ['Contento', 'Arrepentido', 'Desafiante', 'Curioso'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 25/37',
    image: '/images/images25.jpg',
    options: ['Pensativo', 'Irritado', 'Entusiasmado', 'Hostil'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 26/37',
    image: '/images/images26.jpg',
    options: ['Alarmado', 'Incrédulo', 'Desalentado', 'Interesado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 27/37',
    image: '/images/images27.jpg',
    options: ['Alarmado', 'Tímido', 'Hostil', 'Ansioso'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 28/37',
    image: '/images/images28.jpg',
    options: ['Bromeando', 'Cauteloso', 'Arrogante', 'Tranquilizadora'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 29/37',
    image: '/images/images29.jpg',
    options: ['Interesado', 'Bromeando', 'Cariñoso', 'Contento'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 30/37',
    image: '/images/images30.jpg',
    options: ['Impaciente', 'Espantado', 'Irritado', 'Reflexivo'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 31/37',
    image: '/images/images31.jpg',
    options: ['Agradecido', 'Coqueto', 'Hostil', 'Decepcionado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 32/37',
    image: '/images/images32.jpg',
    options: ['Averagonzado', 'Seguro', 'Bromeando', 'Desanimado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 33/37',
    image: '/images/images33.jpg',
    options: ['Serio', 'Avergonzado', 'Desconcertado', 'Alarmado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 34/37',
    image: '/images/images34.jpg',
    options: ['Averagonzado', 'Culpable', 'Fantaseoso', 'Intranquilo'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 35/37',
    image: '/images/images35.jpg',
    options: ['Espantado', 'Perplejo', 'Desconfiado', 'Aterrado'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 36/37',
    image: '/images/images36.jpg',
    options: ['Perplejo', 'Nervioso', 'Insistente', 'Contemplativo'],
  },
  {
    type: 'image',
    question: '¿Cual es la emoción de esta mirada? 37/37',
    image: '/images/images37.jpg',
    options: ['Avergonzado', 'Nervioso', 'Desconfiado', 'Indeciso'],
  },
];